---
{
   "kind": "pipeline",
   "name": "main",
   "platform": {
      "arch": "amd64",
      "os": "linux"
   },
   "steps": [
      {
         "commands": [
            "go test -v ./..."
         ],
         "image": "golang",
         "name": "test"
      },
   ],
   "trigger": {
      "branch": [
         "main"
      ]
   },
   "type": "kubernetes"
}
